### ISSUE TITLE
subinclude support for menu, article creation

### ISSUE THREAD

**Issue by ngdot** [oveleon/contao-page-duplicate-bundle#1]
Hi, first of all – this extension is soooo goooooooood! Exactly what I missed for years – 10000x thanks for this!

There is a bug, which makes it not able to show the the sub includes in a menu of a main include page if it's active (trail?).
In my example below "Aktiver Menüpunkt" is a page duplicate, but also the sites below "Unterpunkt 1" & "Unterpunkt 2".

Is status:
![SCR-20221028-b6e](https://user-images.githubusercontent.com/8327905/198514880-1d182a3e-75ea-4ffd-8cd6-983d77d78c26.png)
Should be:
![SCR-20221028-b79](https://user-images.githubusercontent.com/8327905/198514882-75e27c3d-a1ca-423b-90c1-77f822bcb918.png)

And maybe it's possible to disable the automatic article creation if the page duplicate page typ is used.

**Comment by zoglo** [comment]
As already mentioned on Slack, this Bundle does not have much priority for us and was simply created and updated for a specific project with content-managers and easy content-creation in mind.

I do not suggest having duplicates on the same website due to SEO-aspects.

The first problem:
- there is currently no Hooks for an "unknown" pagetype for ModuleNavigation. Without a PR in the core-bundle, this won't be an easy task.

Your second problem:
- sadly, it's coded very statically and you can't add another page type to disable the automatic article generation:
https://github.com/contao/core-bundle/blob/fb758c19fa5151626fa99787bf5c43fa93d38345/src/Routing/Page/PageRegistry.php#L20
